---
- name: Install curl
  apt: pkg=curl state=latest
  sudo: yes
  sudo_pass: "{{ sudo_pass }}"
  when: ansible_os_family == "Debian"

- name: Install curl
  homebrew: name=curl state=latest update_homebrew=yes
  when: ansible_os_family == "Darwin"
